<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Include="HART.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LayeredArchitecture.Domain\LayeredArchitecture.Domain.csproj" />
    <ProjectReference Include="..\LayeredArchitecture.Application\LayeredArchitecture.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
